### ISSUE TITLE
I really don't understand this.

### ISSUE THREAD

**Issue by WendyStarfall** [NorthGlenwalker/OpenCollarIW#1]
Why would you make this look as if we were somehow against InWorldz having a working device and how are you "forced" to completely trample over all history?

The reason for the OpenCollarHypergrid repository to be discontinued in the first place was because it was a copy, not a proper fork. The group notice recommended people to work on actual forks.

What you did on OpenCollarHypergrid was to delete files and replace them with almost identical files of older version but renamed with "IW" at the end, then you merged the InWorldz branch into the branch that was supposed to be the common canvas for all devices on OpenSimulator. Along the way, you also rummaged the Animation Overrider into the wrong repository, again erasing all history for that source.

What speaks against using a fork of the OpenCollarUpdater and the OpenCollarAO?

Why aren't you giving attribution to anyone?

Why don't you state any changes?

Why is the GPL not attached here?

Why do you keep erasing all history?

How are you "forced" to do all that?

Either you lack all fundamental understanding of git version control or you have no scrouples to dress yourself with other people's laurels.

The latter would explain why you are so eager to make OpenCollar repeatedly look bad.

**Comment by NorthGlenwalker** [comment]
After spending 4 hours yesterday collecting all the code changes in IW from different people and then re uploading everything, as the only full copy was on the hypergrid, I was shell I say, very fed up and if it wasn't for the fact other people needed the code I would have given up

**Comment by NorthGlenwalker** [comment]
The reason a number of the files are older versions is that most of the current OC files in SL cause other grids to crash (yes actual grid crashes on TAG) we have had to return to older code versions just so we don't crash grids or regions. The IW appended files are to show that these files will not work on any other grid without modification due to the way some code works in IW.

**Comment by GarvinTwine** [comment]
If these few scripts are a capable of crashing the whole IW grid... this seems to be quite the alpha state development grid or you really try to talk that grid serious down for its unreliability that i wonder why you would try to get any code up to such a unreliable unstable platform... (no offend ment to the creators, developers and supporters of IW, i am sure this is somehow a misunderstanding)
When people use github and use open source codes others created in years of development it should be more than common sense to make sure whatever you do that the  history of the code and development stays in place for all to see. So please learn how to do things right on github instead of just copy pasting code from a to b with the effect of losing all history.
Thank you very much and you are welcome to spread the code if you do it the right way.
